language: php
dist: bionic
os: linux

php:
    - 7.2
    - 7.3
    - 7.4
    - hhvm

services:
  - mysql

before_script:
  - composer install
  - mysql --version
  - mysql -e 'create database phpauthtest;'
  - mysql -u root phpauthtest < database_defs/database_mysql.sql
  - phpenv config-rm xdebug.ini || return 0
  
script:
- echo "skipping tests"
  
matrix:
    allow_failures:
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: hhvm
    fast_finish: true

deploy:
    provider: pages
    cleanup: true
    token: $GITHUB_TOKEN
    local_dir: output
    strategy: git
    on:
        branch: master

notifications:
    email: false
