language: php
dist: bionic
os: linux

php:
    - 7.2
    - 7.3
    - 7.4

services:
  - mysql

before_script:
  - composer install
  - mysql --version
  - mysql -e 'create database phpauthtest;'
  - mysql -u root phpauthtest < database_defs/database_mysql.sql
  - phpenv config-rm xdebug.ini || return 0

deploy:
    provider: pages
    cleanup: true
    token: $GITHUB_TOKEN
    local_dir: output
    strategy: git
    on:
        branch: master

notifications:
    email: false
